### PR TITLE
Feat rpc

### PR DESCRIPTION
**Pull request by DerXanRam**
I know the code have some luck of efficiency and format that u give me to follow. But i failed to deliver and i'm sorry. at-list , until i fully make it, it gives some idea for some one who want to interact with blockchain and known DEXs using c++ or c.

### CODE REVIEW

**Comment by mhw0** [comment]
Hello. That doesn't look that bad. I love how you called methods like `eth_call`, `eth_getBalance`, `eth_sendRawTransaction`. 

I'm thinking about this:

diagram

**Comment by mhw0** [comment]
I think we need to create the http layer first. And then other layers can be built on top of it.

**Comment by mhw0** [comment]
and, what happened to the first PR? Should I close it?

**Comment by DerXanRam** [comment]
I try to add this PR ont that and i can't so i do this :smile:  sorry for my mess. u can close that because this PR have also the previous PR's feature.

**Comment by mhw0** [comment]
Please use this PR for future updates.

**Pull request closed without merging**
